version: '3.7'

services:
  makepdfs:
    container_name: google-drive-action
    build:
      context: .
      dockerfile: Dockerfile
    image: "docker.pkg.github.com/addresscloud/google-drive-action/google-drive-action:${TAG:-latest}"
